<a href="https://colab.research.google.com/github/Redcoder815/AI_programming_with_python/blob/main/15PandasRecap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [8]:
df = pd.read_csv("/content/student_data (1).csv")
df.columns
arr = np.array(df.columns)
print(arr.dtype)
print(arr)

object
['StudentID' 'FullName' 'Data Structure Marks' 'Algorithm Marks'
 'Python Marks' 'CompletionStatus' 'EnrollmentDate' 'Instructor'
 'Location']

In [6]:
df.index

RangeIndex(start=0, stop=20, step=1)

In [7]:
ind = np.array(df.index)
print(ind)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

In [9]:
df.sample(10)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka

In [10]:
my_list = [['Alice', 25], ['Bob', 30], ['Charlie', 28]]

list_df = pd.DataFrame(my_list, columns = ["Name", "Age"], index = [1,2,3])
print(list_df)

      Name  Age
1    Alice   25
2      Bob   30
3  Charlie   28

In [11]:
my_data = [
    {'Name': 'Alice', 'Age': 25, 'City': 'New York'},
    {'Name': 'Bob', 'Age': 30, 'City': 'Paris'},
    {'Name': 'Charlie', 'Age': 28}
]

list_df = pd.DataFrame(my_data)
print(list_df)

      Name  Age      City
0    Alice   25  New York
1      Bob   30     Paris
2  Charlie   28       NaN

In [12]:
df['FullName']

0          Alif Rahman
1        Fatima Akhter
2        Imran Hossain
3     Jannatul Ferdous
4          Kamal Uddin
5          Laila Begum
6       Mahmudul Hasan
7          Nadia Islam
8           Omar Faruq
9         Priya Sharma
10        Rahim Sheikh
11     Sadia Chowdhury
12        Tanvir Ahmed
13          Urmi Akter
14        Wahiduzzaman
15        Ziaur Rahman
16         Afsana Mimi
17         Babul Ahmed
18        Faria Rahman
19          Nasir Khan
Name: FullName, dtype: object

In [14]:
df.loc[0]

StudentID                    PH1001
FullName                Alif Rahman
Data Structure Marks           85.0
Algorithm Marks                85.0
Python Marks                   88.0
CompletionStatus          Completed
EnrollmentDate           2024-01-15
Instructor                Mr. Karim
Location                      Dhaka
Name: 0, dtype: object

In [15]:
df.loc[[2,3,19]]

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [16]:
df.loc[3:7]

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram

In [18]:
df.loc[:,'Python Marks']

0     88.0
1      NaN
2     85.0
3     82.0
4     95.0
5     78.0
6      NaN
7     85.0
8     76.0
9     88.0
10    91.0
11    87.0
12    79.0
13     NaN
14    84.0
15     NaN
16    93.0
17    85.0
18     NaN
19    89.0
Name: Python Marks, dtype: float64

In [19]:
df.loc[:,['Python Marks', 'Algorithm Marks']]

    Python Marks  Algorithm Marks
0           88.0             85.0
1            NaN             92.0
2           85.0             88.0
3           82.0             78.0
4           95.0              NaN
5           78.0             75.0
6            NaN             80.0
7           85.0             81.0
8           76.0             72.0
9           88.0             89.0
10          91.0              NaN
11          87.0             85.0
12          79.0             75.0
13           NaN              NaN
14          84.0             86.0
15           NaN             94.0
16          93.0             90.0
17          85.0             88.0
18           NaN              NaN
19          89.0             86.0

In [20]:
df.loc[3:7, 'CompletionStatus']

3      Completed
4    In Progress
5      Completed
6    In Progress
7      Completed
Name: CompletionStatus, dtype: object

In [21]:
df_index = df.set_index('StudentID')
df_index

,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
StudentID,,,,,,,,
PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [22]:
df_index.iloc[:,0:5]

,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus
StudentID,,,,,
PH1001,Alif Rahman,85.0,85.0,88.0,Completed
PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress
PH1003,Imran Hossain,88.0,88.0,85.0,Completed
PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed
PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress
PH1006,Laila Begum,75.0,75.0,78.0,Completed
PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress
PH1008,Nadia Islam,81.0,81.0,85.0,Completed
PH1009,Omar Faruq,72.0,72.0,76.0,Completed
PH1010,Priya Sharma,89.0,89.0,88.0,Completed
PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress
PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed
PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed
PH1014,Urmi Akter,NaN,NaN,NaN,Not Started
PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed
PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress
PH1017,Afsana Mimi,90.0,90.0,93.0,Completed
PH1018,Babul Ahmed,88.0,88.0,85.0,Completed
PH1019,Faria Rahman,NaN,NaN,NaN,Not Started
PH1020,Nasir Khan,86.0,86.0,89.0,Completed

In [23]:
df.rename(columns = {'FullName':'Full Name', 'AlgorithmMarks':'Algo Marks'}, inplace=True)
df

,StudentID,Full Name,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [24]:
df.drop(0, inplace=True)
df

,StudentID,Full Name,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [29]:
df.drop('Location',axis = 1, inplace=True)
df

,StudentID,Full Name,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02

In [30]:
df.loc[1, 'Python Marks'] = 90
df.loc[1, 'CompletionStatus'] = 'Completed'
df.head(5)

,StudentID,Full Name,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate
1,PH1002,Fatima Akhter,92.0,92.0,90.0,Completed,2024-01-20
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08

In [33]:
df.loc[1:3,'Python Marks'] += 2
df.head(5)

,StudentID,Full Name,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate
1,PH1002,Fatima Akhter,92.0,92.0,92.0,Completed,2024-01-20
2,PH1003,Imran Hossain,88.0,88.0,87.0,Completed,2024-02-10
3,PH1004,Jannatul Ferdous,78.0,78.0,84.0,Completed,2024-02-12
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08

In [34]:
for i, series in df.iterrows():
  print(f"{i} : {series}")

1 : StudentID                      PH1002
Full Name               Fatima Akhter
Data Structure Marks             92.0
Algorithm Marks                  92.0
Python Marks                     92.0
CompletionStatus            Completed
EnrollmentDate             2024-01-20
Name: 1, dtype: object
2 : StudentID                      PH1003
Full Name               Imran Hossain
Data Structure Marks             88.0
Algorithm Marks                  88.0
Python Marks                     87.0
CompletionStatus            Completed
EnrollmentDate             2024-02-10
Name: 2, dtype: object
3 : StudentID                         PH1004
Full Name               Jannatul Ferdous
Data Structure Marks                78.0
Algorithm Marks                     78.0
Python Marks                        84.0
CompletionStatus               Completed
EnrollmentDate                2024-02-12
Name: 3, dtype: object
4 : StudentID                    PH1005
Full Name               Kamal Uddin
Data Structure Marks            NaN
Algorithm Marks                 NaN
Python Marks                   95.0
CompletionStatus        In Progress
EnrollmentDate           2024-03-05
Name: 4, dtype: object
5 : StudentID                    PH1006
Full Name               Laila Begum
Data Structure Marks           75.0
Algorithm Marks                75.0
Python Marks                   78.0
CompletionStatus          Completed
EnrollmentDate           2024-03-08
Name: 5, dtype: object
6 : StudentID                       PH1007
Full Name               Mahmudul Hasan
Data Structure Marks              80.0
Algorithm Marks                   80.0
Python Marks                       NaN
CompletionStatus           In Progress
EnrollmentDate              2024-04-01
Name: 6, dtype: object
7 : StudentID                    PH1008
Full Name               Nadia Islam
Data Structure Marks           81.0
Algorithm Marks                81.0
Python Marks                   85.0
CompletionStatus          Completed
EnrollmentDate           2024-04-22
Name: 7, dtype: object
8 : StudentID                   PH1009
Full Name               Omar Faruq
Data Structure Marks          72.0
Algorithm Marks               72.0
Python Marks                  76.0
CompletionStatus         Completed
EnrollmentDate          2024-05-16
Name: 8, dtype: object
9 : StudentID                     PH1010
Full Name               Priya Sharma
Data Structure Marks            89.0
Algorithm Marks                 89.0
Python Marks                    88.0
CompletionStatus           Completed
EnrollmentDate            2024-05-20
Name: 9, dtype: object
10 : StudentID                     PH1011
Full Name               Rahim Sheikh
Data Structure Marks             NaN
Algorithm Marks                  NaN
Python Marks                    91.0
CompletionStatus         In Progress
EnrollmentDate            2024-06-11
Name: 10, dtype: object
11 : StudentID                        PH1012
Full Name               Sadia Chowdhury
Data Structure Marks               85.0
Algorithm Marks                    85.0
Python Marks                       87.0
CompletionStatus              Completed
EnrollmentDate               2024-06-14
Name: 11, dtype: object
12 : StudentID                     PH1013
Full Name               Tanvir Ahmed
Data Structure Marks            75.0
Algorithm Marks                 75.0
Python Marks                    79.0
CompletionStatus           Completed
EnrollmentDate            2024-07-02
Name: 12, dtype: object
13 : StudentID                    PH1014
Full Name                Urmi Akter
Data Structure Marks            NaN
Algorithm Marks                 NaN
Python Marks                    NaN
CompletionStatus        Not Started
EnrollmentDate           2024-07-09
Name: 13, dtype: object
14 : StudentID                     PH1015
Full Name               Wahiduzzaman
Data Structure Marks            86.0
Algorithm Marks                 86.0
Python Marks                    84.0
CompletionStatus           Completed
EnrollmentDate            2024-08-18
Name: 14, dtype: object
15 : StudentID                     PH1016
Full Name               Ziaur Rahman
Data Structure Marks            94.0
Algorithm Marks                 94.0
Python Marks                     NaN
CompletionStatus         In Progress
EnrollmentDate            2024-08-21
Name: 15, dtype: object
16 : StudentID                    PH1017
Full Name               Afsana Mimi
Data Structure Marks           90.0
Algorithm Marks                90.0
Python Marks                   93.0
CompletionStatus          Completed
EnrollmentDate           2025-09-01
Name: 16, dtype: object
17 : StudentID                    PH1018
Full Name               Babul Ahmed
Data Structure Marks           88.0
Algorithm Marks                88.0
Python Marks                   85.0
CompletionStatus          Completed
EnrollmentDate           2025-09-05
Name: 17, dtype: object
18 : StudentID                     PH1019
Full Name               Faria Rahman
Data Structure Marks             NaN
Algorithm Marks                  NaN
Python Marks                     NaN
CompletionStatus         Not Started
EnrollmentDate            2025-09-15
Name: 18, dtype: object
19 : StudentID                   PH1020
Full Name               Nasir Khan
Data Structure Marks          86.0
Algorithm Marks               86.0
Python Marks                  89.0
CompletionStatus         Completed
EnrollmentDate          2025-10-02
Name: 19, dtype: object

In [35]:
for i in df.itertuples(index = False):
  print(i)

Pandas(StudentID='PH1002', _1='Fatima Akhter', _2=92.0, _3=92.0, _4=92.0, CompletionStatus='Completed', EnrollmentDate='2024-01-20')
Pandas(StudentID='PH1003', _1='Imran Hossain', _2=88.0, _3=88.0, _4=87.0, CompletionStatus='Completed', EnrollmentDate='2024-02-10')
Pandas(StudentID='PH1004', _1='Jannatul Ferdous', _2=78.0, _3=78.0, _4=84.0, CompletionStatus='Completed', EnrollmentDate='2024-02-12')
Pandas(StudentID='PH1005', _1='Kamal Uddin', _2=nan, _3=nan, _4=95.0, CompletionStatus='In Progress', EnrollmentDate='2024-03-05')
Pandas(StudentID='PH1006', _1='Laila Begum', _2=75.0, _3=75.0, _4=78.0, CompletionStatus='Completed', EnrollmentDate='2024-03-08')
Pandas(StudentID='PH1007', _1='Mahmudul Hasan', _2=80.0, _3=80.0, _4=nan, CompletionStatus='In Progress', EnrollmentDate='2024-04-01')
Pandas(StudentID='PH1008', _1='Nadia Islam', _2=81.0, _3=81.0, _4=85.0, CompletionStatus='Completed', EnrollmentDate='2024-04-22')
Pandas(StudentID='PH1009', _1='Omar Faruq', _2=72.0, _3=72.0, _4=76.0, CompletionStatus='Completed', EnrollmentDate='2024-05-16')
Pandas(StudentID='PH1010', _1='Priya Sharma', _2=89.0, _3=89.0, _4=88.0, CompletionStatus='Completed', EnrollmentDate='2024-05-20')
Pandas(StudentID='PH1011', _1='Rahim Sheikh', _2=nan, _3=nan, _4=91.0, CompletionStatus='In Progress', EnrollmentDate='2024-06-11')
Pandas(StudentID='PH1012', _1='Sadia Chowdhury', _2=85.0, _3=85.0, _4=87.0, CompletionStatus='Completed', EnrollmentDate='2024-06-14')
Pandas(StudentID='PH1013', _1='Tanvir Ahmed', _2=75.0, _3=75.0, _4=79.0, CompletionStatus='Completed', EnrollmentDate='2024-07-02')
Pandas(StudentID='PH1014', _1='Urmi Akter', _2=nan, _3=nan, _4=nan, CompletionStatus='Not Started', EnrollmentDate='2024-07-09')
Pandas(StudentID='PH1015', _1='Wahiduzzaman', _2=86.0, _3=86.0, _4=84.0, CompletionStatus='Completed', EnrollmentDate='2024-08-18')
Pandas(StudentID='PH1016', _1='Ziaur Rahman', _2=94.0, _3=94.0, _4=nan, CompletionStatus='In Progress', EnrollmentDate='2024-08-21')
Pandas(StudentID='PH1017', _1='Afsana Mimi', _2=90.0, _3=90.0, _4=93.0, CompletionStatus='Completed', EnrollmentDate='2025-09-01')
Pandas(StudentID='PH1018', _1='Babul Ahmed', _2=88.0, _3=88.0, _4=85.0, CompletionStatus='Completed', EnrollmentDate='2025-09-05')
Pandas(StudentID='PH1019', _1='Faria Rahman', _2=nan, _3=nan, _4=nan, CompletionStatus='Not Started', EnrollmentDate='2025-09-15')
Pandas(StudentID='PH1020', _1='Nasir Khan', _2=86.0, _3=86.0, _4=89.0, CompletionStatus='Completed', EnrollmentDate='2025-10-02')

In [36]:
copy = df.sort_values('Data Structure Marks')
copy

,StudentID,Full Name,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02
3,PH1004,Jannatul Ferdous,78.0,78.0,84.0,Completed,2024-02-12
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05
2,PH1003,Imran Hossain,88.0,88.0,87.0,Completed,2024-02-10
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01
1,PH1002,Fatima Akhter,92.0,92.0,92.0,Completed,2024-01-20
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15

In [37]:
copy = df.sort_values(['Data Structure Marks'],ascending=False)

copy

,StudentID,Full Name,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21
1,PH1002,Fatima Akhter,92.0,92.0,92.0,Completed,2024-01-20
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05
2,PH1003,Imran Hossain,88.0,88.0,87.0,Completed,2024-02-10
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01
3,PH1004,Jannatul Ferdous,78.0,78.0,84.0,Completed,2024-02-12
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15

In [38]:
copy = df.sort_values(['Data Structure Marks','Python Marks'], ascending = False)
copy

,StudentID,Full Name,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21
1,PH1002,Fatima Akhter,92.0,92.0,92.0,Completed,2024-01-20
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20
2,PH1003,Imran Hossain,88.0,88.0,87.0,Completed,2024-02-10
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01
3,PH1004,Jannatul Ferdous,78.0,78.0,84.0,Completed,2024-02-12
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15

In [39]:
copy = df.sort_values(['Data Structure Marks','Python Marks'],ascending=[0,1])

copy

,StudentID,Full Name,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21
1,PH1002,Fatima Akhter,92.0,92.0,92.0,Completed,2024-01-20
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05
2,PH1003,Imran Hossain,88.0,88.0,87.0,Completed,2024-02-10
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01
3,PH1004,Jannatul Ferdous,78.0,78.0,84.0,Completed,2024-02-12
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15

In [40]:
not_started = df.loc[df['CompletionStatus'] == 'Not Started']
not_started

,StudentID,Full Name,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15

In [42]:
completed_90 = df.loc[(df['CompletionStatus'] == 'Completed') & (df['Algorithm Marks'] >= 90)]
completed_90

,StudentID,Full Name,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate
1,PH1002,Fatima Akhter,92.0,92.0,92.0,Completed,2024-01-20
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01