<a href="https://colab.research.google.com/github/Redcoder815/AI_programming_with_python/blob/main/16PandasPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

Create a Pandas Series from the list [10, 20, 30, 40, 50]. Print the Series, its index, and data type. Then create a DataFrame with columns "Name", "Age", and "City" containing at least 4 rows of data.

In [2]:
data_list = [10, 20, 30, 40, 50]

df = pd.Series(data_list)
print(df)

print(np.array(df.index))
print(df.index)
print(df.dtype)

0    10
1    20
2    30
3    40
4    50
dtype: int64
[0 1 2 3 4]
RangeIndex(start=0, stop=5, step=1)
int64

In [3]:
df_data = [
    {"Name": "Alice", "Age": 28, "City": "New York"},
    {"Name": "Bob", "Age": 34, "City": "Chicago"},
    {"Name": "Charlie", "Age": 22, "City": "San Francisco"},
    {"Name": "Diana", "Age": 31, "City": "Austin"}
]
df = pd.DataFrame(df_data)
print(df)

      Name  Age           City
0    Alice   28       New York
1      Bob   34        Chicago
2  Charlie   22  San Francisco
3    Diana   31         Austin



Using any DataFrame, write code to print the number of rows and columns, column data types (.dtypes), and summary statistics (.describe()).

In [4]:
print("Number of rows and columns ", df.shape)
print("column data types ", df.dtypes)
# print(df.dtypes)
print(df.describe())

Number of rows and columns  (4, 3)
column data types  Name    object
Age      int64
City    object
dtype: object
             Age
count   4.000000
mean   28.750000
std     5.123475
min    22.000000
25%    26.500000
50%    29.500000
75%    31.750000
max    34.000000

In [5]:
data = {
    'Product': ['Pen', 'Book', 'Eraser', 'Pencil'],
    'Price': [10, 50, 5, 7],
    'Quantity': [100, 60, 200, 150]
}

df = pd.DataFrame(data)
print(df)
print("Print columns ", df.columns)
print("Index ", df.index)
print(df.iloc[1])
df['Price']

  Product  Price  Quantity
0     Pen     10       100
1    Book     50        60
2  Eraser      5       200
3  Pencil      7       150
Print columns  Index(['Product', 'Price', 'Quantity'], dtype='object')
Index  RangeIndex(start=0, stop=4, step=1)
Product     Book
Price         50
Quantity      60
Name: 1, dtype: object

0    10
1    50
2     5
3     7
Name: Price, dtype: int64

Using .loc[] and .iloc[], show the first row, the second column, and a 2×2 block    from the middle of your DataFrame.

In [6]:
print(df.loc[0])
print(df.iloc[0:1,:])
print(df.iloc[:,1])
#2x2 block from the middle of dataframe
print(df.iloc[1:3,0:2])
print(df.loc[1:2, ['Product', 'Price']])

Product     Pen
Price        10
Quantity    100
Name: 0, dtype: object
  Product  Price  Quantity
0     Pen     10       100
0    10
1    50
2     5
3     7
Name: Price, dtype: int64
  Product  Price
1    Book     50
2  Eraser      5
  Product  Price
1    Book     50
2  Eraser      5

In [7]:
df.drop(0, axis = 0)
df.drop('Price', axis = 1)

  Product  Quantity
0     Pen       100
1    Book        60
2  Eraser       200
3  Pencil       150

In [8]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Ethan'],
    'Department': ['HR', 'IT', 'Finance', 'IT', 'Marketing'],
    'Salary': [50000, 70000, 65000, 72000, 58000]
}

df = pd.DataFrame(data)

print(df)

      Name Department  Salary
0    Alice         HR   50000
1      Bob         IT   70000
2  Charlie    Finance   65000
3    Diana         IT   72000
4    Ethan  Marketing   58000

In [9]:
copy = df.sort_values(['Salary', 'Name'], ascending=[0,1])
copy

      Name Department  Salary
3    Diana         IT   72000
1      Bob         IT   70000
2  Charlie    Finance   65000
4    Ethan  Marketing   58000
0    Alice         HR   50000

In [10]:
student_data = {
    'Name': ['Liam', 'Sophia', 'Noah', 'Emma', 'Oliver', 'Ava', 'Ethan', 'Isabella'],
    'Score': [85, 92, 78, 95, 88, 70, 82, 91]
}

df = pd.DataFrame(student_data)

print(df)

       Name  Score
0      Liam     85
1    Sophia     92
2      Noah     78
3      Emma     95
4    Oliver     88
5       Ava     70
6     Ethan     82
7  Isabella     91

In [11]:
slicing_data = df.loc[(df['Score'] > 80)]
slicing_data

       Name  Score
0      Liam     85
1    Sophia     92
3      Emma     95
4    Oliver     88
6     Ethan     82
7  Isabella     91